### ISSUE TITLE
Internet connection refused

### ISSUE THREAD

**Issue by krutzy62** [dslotter/wsjtx_to_n3fjp#2]
Dave,

I have an error that I am trying figure out.

What I am trying to log my remote WSJT-X to my running N3FJP at home.  I thought through everything.   I use JTAlert on my home PC.  I have the port 1100 on both sides.  The url is my Apt IP address which is dynamic and updated on a regular basis.  

The configuration and what I get from your python script is below.  Do you have any ideas?  

Thanks you.
73, Kevin KX4KU

[config py.pdf](https://github.com/dslotter/wsjtx_to_n3fjp/files/5930353/config.py.pdf)
[Log Failure.pdf](https://github.com/dslotter/wsjtx_to_n3fjp/files/5930354/Log.Failure.pdf)

**Comment by dslotter** [comment]
Is port 1100 open on the router connected to kuapt.ddns.net? That's the only thing I can think of.

Try yourself -- make sure you can reach port 1100 on kuapt.ddns.net from the machine running wsjtx_to_n3fjp. If you can't, then you have to correct that for the script to work.

**Comment by krutzy62** [comment]
Dave,
Thank you and yes I did check open port check tool on the web.  However - I know where the problem is - I left the updater of the DNS on the pi on.  I need to kill that process.  Sorry.  But it was helpful to know that I had the config correct.
73,
Kevin, KX4KU

**Comment by krutzy62** [comment]
The program works great!  What a help.
